index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

add_user:
    path: /user/add_user
    methods: POST
    controller: App\Controller\UserController::saveUserToDatabase
    
show_user:
    path: /user/show/{userId}
    controller: App\Controller\UserController::showUser
    methods: GET

update_user:
    path: /user/update
    controller: App\Controller\UserController::updateUserData
    methods: POST

delete_user:
    path: /user/delete
    controller: App\Controller\UserController::deleteUserFromDatabase
    methods: POST

home:
    path: /user/list
    controller: App\Controller\UserController::showUsersList
    methods: GET